export { default as SettingLabels, SettingLabel } from './label'
export { default as VerticalSetting } from './vertical'
export { default as DropDownSetting } from './dropdown'
export { default as SwitchSetting } from './switch'
export { default as SettingLayout, SettingTab, settings } from './main'
