enum Setting {
    SAFE_MODE = "UPDATE_SAFE_MODE",
    FULL_CENSOR = "UPDATE_FULL_CENSOR",
    DEFAULT_PREFERENCE = "UPDATE_DEFAULT_PREFERENCE",
    ADD_PREFERENCE = "ADD_PREFERENCE",
    REMOVE_PREFERENCE = "REMOVE_PREFERENCE",
    SET_PREFERENCE = "SET_PREFERENCE",
    UPDATE_DEFAULT_FILTER = "UPDATE_DEFAULT_FILTER",
    ADD_FILTER = "ADD_FILTER",
    REMOVE_FILTER = "REMOVE_FILTER",
    SET_FILTER = "SET_FILTER"
}

export default Setting